/**
 * Demo persona seed-payload builder — pure, no IO. Productizes tonight's
 * manual seed SQL (Maya Thompson's journey) into a reusable function:
 * given a target person id (and a few pre-generated child-row ids so
 * cross-references resolve without a live DB round trip), returns every
 * row the route needs to insert to give that person a coherent journey
 * — discipleship milestones, journey goals, a group membership, a
 * recurring gift sized to the church's configured giving tiers, a
 * couple of one-time gifts, a public prayer post, an event RSVP, an
 * approved KYC + funded Impact Card + a small interchange history, and
 * a member_activity_events trail.
 *
 * Every row traces back to the person via person_id, and the person
 * itself carries tags: ['demo-persona'] plus a notes marker — the
 * durable way to find (and, if ever needed, clean up) everything this
 * function seeded. Tables with a metadata JSONB column additionally get
 * { demo: true } on each row.
 */

const WEEKLY_DIVISOR: Record<string, number> = {
  weekly: 1,
  monthly: 52 / 12,
  quarterly: 52 / 4,
  annually: 52,
};

const DEFAULT_RECURRING_WEEKLY_AMOUNT = 25;

export interface GivingTierDefinition {
  label: string;
  weeklyThreshold: number;
}

export interface DemoPersonaInput {
  churchId: string;
  /** Pre-generated by the caller (crypto.randomUUID()) so every child row's FK resolves without a live round trip. */
  personId: string;
  kycId: string;
  cardId: string;
  cardAccountId: string;
  firstName: string;
  lastName: string;
  now: Date;
  /** Church's churches.settings.givingTiers, if configured. */
  givingTiers?: GivingTierDefinition[];
  /** The church's first active small_groups row, if one exists — skip group membership entirely rather than fabricate a group. */
  firstActiveGroupId?: string | null;
  /** The next upcoming calendar_events row, if one exists — skip the RSVP entirely rather than fabricate an event. */
  nextUpcomingEventId?: string | null;
}

export interface DemoPersonaSeedPayload {
  person: Record<string, unknown>;
  discipleshipMilestones: Record<string, unknown>[];
  journeyItems: Record<string, unknown>[];
  groupMembership: Record<string, unknown> | null;
  recurringGift: Record<string, unknown>;
  givingTierNote: string | null;
  oneTimeGifts: Record<string, unknown>[];
  prayerPost: Record<string, unknown>;
  eventRsvp: Record<string, unknown> | null;
  kyc: Record<string, unknown>;
  card: Record<string, unknown>;
  cardAccount: Record<string, unknown>;
  interchangeEvents: Record<string, unknown>[];
  activityEvents: Record<string, unknown>[];
}

function daysAgo(now: Date, days: number): string {
  return new Date(now.getTime() - days * 86_400_000).toISOString();
}

export function buildDemoPersonaSeed(input: DemoPersonaInput): DemoPersonaSeedPayload {
  const {
    churchId, personId, kycId, cardId, cardAccountId,
    firstName, lastName, now, givingTiers, firstActiveGroupId, nextUpcomingEventId,
  } = input;

  const fullName = `${firstName} ${lastName}`;
  const demoEmail = `${firstName.toLowerCase()}.${lastName.toLowerCase()}+demo@grace-crm.internal`;
  const nowIso = now.toISOString();

  const person = {
    id: personId,
    church_id: churchId,
    first_name: firstName,
    last_name: lastName,
    email: demoEmail,
    status: 'member',
    join_date: daysAgo(now, 120).slice(0, 10),
    first_visit: daysAgo(now, 150).slice(0, 10),
    tags: ['demo-persona'],
    notes: '[Demo persona] Seeded via Provisioning Studio — synthetic data for testing and demos, not a real congregant.',
  };

  const discipleshipMilestones = [
    { church_id: churchId, person_id: personId, milestone_type: 'first_visit', completed_at: daysAgo(now, 150), notes: '[demo]' },
    { church_id: churchId, person_id: personId, milestone_type: 'attended_class', completed_at: daysAgo(now, 90), notes: '[demo]' },
    { church_id: churchId, person_id: personId, milestone_type: 'baptized', completed_at: daysAgo(now, 60), notes: '[demo]' },
  ];

  const journeyItems = [
    {
      church_id: churchId, person_id: personId, item_type: 'goal',
      title: 'Join a small group', description: '[demo] Seeded journey goal.', status: 'active',
    },
    {
      church_id: churchId, person_id: personId, item_type: 'goal',
      title: 'Serve on a ministry team', description: '[demo] Seeded journey goal.', status: 'active',
    },
  ];

  const groupMembership = firstActiveGroupId
    ? { church_id: churchId, group_id: firstActiveGroupId, person_id: personId, status: 'active', joined_at: daysAgo(now, 45) }
    : null;

  const sortedTiers = [...(givingTiers ?? [])].sort((a, b) => b.weeklyThreshold - a.weeklyThreshold);
  const targetTier = sortedTiers[0];
  const recurringWeeklyAmount = targetTier ? targetTier.weeklyThreshold : DEFAULT_RECURRING_WEEKLY_AMOUNT;
  const recurringGift = {
    church_id: churchId,
    person_id: personId,
    amount: recurringWeeklyAmount * (WEEKLY_DIVISOR.weekly),
    frequency: 'weekly',
    fund: 'tithe',
    next_date: daysAgo(now, -7).slice(0, 10),
    status: 'active',
  };
  const givingTierNote = targetTier
    ? null
    : 'No giving tiers configured for this church — seeded a $25/week recurring gift with no tier assignment.';

  const oneTimeGifts = [
    { church_id: churchId, person_id: personId, amount: 50, fund: 'offering', date: daysAgo(now, 30).slice(0, 10), method: 'online', is_recurring: false, note: '[demo]' },
    { church_id: churchId, person_id: personId, amount: 100, fund: 'missions', date: daysAgo(now, 10).slice(0, 10), method: 'online', is_recurring: false, note: '[demo]' },
  ];

  const prayerPost = {
    church_id: churchId,
    person_id: personId,
    content: '[Demo] Grateful for this community and asking for continued strength this season.',
    is_private: false,
    is_answered: false,
    visibility: 'church_prayer_wall',
    status: 'active',
    crisis_flagged: false,
  };

  const eventRsvp = nextUpcomingEventId
    ? { church_id: churchId, event_id: nextUpcomingEventId, person_id: personId, status: 'yes', guest_count: 0, source: 'admin' }
    : null;

  const kyc = {
    id: kycId,
    church_id: churchId,
    person_id: personId,
    full_name: fullName,
    date_of_birth: new Date(now.getFullYear() - 30, now.getMonth(), 1).toISOString().slice(0, 10),
    email: demoEmail,
    status: 'approved',
    i2c_kyc_id: `demo_kyc_${personId.slice(0, 8)}`,
    submitted_at: daysAgo(now, 5),
    reviewed_at: daysAgo(now, 4),
    metadata: { demo: true },
  };

  const card = {
    id: cardId,
    church_id: churchId,
    cardholder_person_id: personId,
    kyc_verification_id: kycId,
    i2c_card_id: `demo_card_${personId.slice(0, 8)}`,
    masked_pan: '•••• •••• •••• 4242',
    cardholder_name: fullName,
    expiry_month: 12,
    expiry_year: now.getFullYear() + 3,
    status: 'active',
    activated_at: daysAgo(now, 4),
    metadata: { demo: true },
  };

  const cardAccount = {
    id: cardAccountId,
    church_id: churchId,
    person_id: personId,
    i2c_account_id: `demo_acct_${personId.slice(0, 8)}`,
    account_name: 'GRACE Impact Card',
    account_number_last4: '4242',
    available_balance_micro_usd: 25_000_000,
    status: 'active',
    last_synced_at: nowIso,
    metadata: { demo: true },
  };

  const interchangeEvents = [
    {
      church_id: churchId, card_id: cardId, i2c_event_id: `demo_evt_${personId.slice(0, 8)}_1`,
      event_type: 'authorization', direction: 'debit', amount_micro_usd: 8_500_000,
      currency: 'USD', merchant_name: 'Corner Grocery', merchant_category: 'grocery',
      occurred_at: daysAgo(now, 3), metadata: { demo: true },
    },
    {
      church_id: churchId, card_id: cardId, i2c_event_id: `demo_evt_${personId.slice(0, 8)}_2`,
      event_type: 'capture', direction: 'debit', amount_micro_usd: 8_500_000,
      currency: 'USD', merchant_name: 'Corner Grocery', merchant_category: 'grocery',
      occurred_at: daysAgo(now, 3), metadata: { demo: true },
    },
    {
      church_id: churchId, card_id: cardId, i2c_event_id: `demo_evt_${personId.slice(0, 8)}_3`,
      event_type: 'authorization', direction: 'debit', amount_micro_usd: 2_200_000,
      currency: 'USD', merchant_name: 'Community Coffee', merchant_category: 'restaurant',
      occurred_at: daysAgo(now, 1), metadata: { demo: true },
    },
  ];

  const activityEvents = [
    { church_id: churchId, person_id: personId, event_type: 'login', created_at: daysAgo(now, 1) },
    { church_id: churchId, person_id: personId, event_type: 'rsvp', created_at: daysAgo(now, 3) },
    { church_id: churchId, person_id: personId, event_type: 'group_join', created_at: daysAgo(now, 45) },
    { church_id: churchId, person_id: personId, event_type: 'milestone_achieved', created_at: daysAgo(now, 60) },
    { church_id: churchId, person_id: personId, event_type: 'login', created_at: daysAgo(now, 0) },
  ];

  return {
    person,
    discipleshipMilestones,
    journeyItems,
    groupMembership,
    recurringGift,
    givingTierNote,
    oneTimeGifts,
    prayerPost,
    eventRsvp,
    kyc,
    card,
    cardAccount,
    interchangeEvents,
    activityEvents,
  };
}
