/**
 * The "Pastor" stage of the Maya -> Me -> Us -> Pastor -> Real Pilot
 * workshop experience (North Star doc): real evidence generated by the
 * congregation's own interaction with the workshop simulation
 * (public.html at /workshop.html -> api/workshop/_simulate.ts), rolled
 * up here for leadership. Every figure on this page comes from a real
 * row a real attendee submitted today — nothing here is a projection
 * invented for the pitch.
 */
import { Users, TrendingUp, Sparkles } from 'lucide-react';
import { useWorkshopEvidence } from '../../hooks/useWorkshopEvidence';

const CAUSE_LABELS: Record<string, string> = {
  missions: 'Missions',
  building: 'Building Fund',
  youth: 'Youth Ministry',
  food_pantry: 'Food Pantry',
  care_fund: 'Care Fund',
};

function formatUsd(n: number): string {
  return n.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
}

export function WorkshopEvidencePage() {
  const { data, isLoading, error, forbidden, refresh } = useWorkshopEvidence();

  if (forbidden) {
    return (
      <div className="p-6 text-sm text-gray-500 dark:text-dark-400">
        You don't have permission to view workshop evidence (requires <code>analytics.view</code>).
      </div>
    );
  }
  if (error) {
    return (
      <div className="p-6 text-sm text-brand-600 dark:text-brand-400">
        {error} — <button onClick={() => void refresh()} className="underline">retry</button>
      </div>
    );
  }
  if (isLoading || !data) {
    return <div className="p-6 text-sm text-gray-500 dark:text-dark-400">Loading workshop evidence…</div>;
  }

  const causeTotals: Record<string, number> = {};
  for (const p of data.participants) {
    for (const a of p.allocations) {
      const share = (p.projectedImpactUsd * a.pct) / 100;
      causeTotals[a.cause] = (causeTotals[a.cause] ?? 0) + share;
    }
  }
  const causeRows = Object.entries(causeTotals).sort((a, b) => b[1] - a[1]);

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-gray-900 dark:text-dark-50">Workshop Evidence</h1>
        <p className="text-sm text-gray-500 dark:text-dark-400 mt-1">
          What your congregation just did in this room — real submissions from <code>/workshop.html</code>, not a hypothetical pitch.
        </p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="rounded-xl border border-gray-200 dark:border-dark-700 bg-white dark:bg-dark-800 p-5">
          <div className="flex items-center gap-2 text-gray-500 dark:text-dark-400 text-xs font-medium uppercase tracking-wide">
            <Users size={14} /> Participants
          </div>
          <div className="text-2xl font-semibold text-gray-900 dark:text-dark-50 mt-1">{data.participantCount}</div>
        </div>
        <div className="rounded-xl border border-gray-200 dark:border-dark-700 bg-white dark:bg-dark-800 p-5">
          <div className="flex items-center gap-2 text-gray-500 dark:text-dark-400 text-xs font-medium uppercase tracking-wide">
            <TrendingUp size={14} /> Total projected impact
          </div>
          <div className="text-2xl font-semibold text-gray-900 dark:text-dark-50 mt-1">{formatUsd(data.totalProjectedImpactUsd)}</div>
        </div>
      </div>

      {causeRows.length > 0 && (
        <div className="rounded-xl border border-gray-200 dark:border-dark-700 bg-white dark:bg-dark-800 p-5">
          <div className="flex items-center gap-2 text-sm font-medium text-gray-900 dark:text-dark-50 mb-3">
            <Sparkles size={15} /> Causes people chose
          </div>
          <div className="space-y-2">
            {causeRows.map(([cause, amount]) => (
              <div key={cause} className="flex items-center justify-between text-sm">
                <span className="text-gray-600 dark:text-dark-300">{CAUSE_LABELS[cause] ?? cause}</span>
                <span className="font-medium text-gray-900 dark:text-dark-50">{formatUsd(amount)}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="rounded-xl border border-gray-200 dark:border-dark-700 bg-white dark:bg-dark-800 overflow-hidden">
        <div className="px-5 py-3 border-b border-gray-200 dark:border-dark-700 text-sm font-medium text-gray-900 dark:text-dark-50">
          Individual submissions
        </div>
        {data.participants.length === 0 ? (
          <div className="p-5 text-sm text-gray-500 dark:text-dark-400">No submissions yet — they'll show up here as soon as someone completes the simulation.</div>
        ) : (
          <div className="divide-y divide-gray-100 dark:divide-dark-700">
            {data.participants.map((p) => (
              <div key={p.id} className="px-5 py-3 flex items-center justify-between text-sm">
                <div>
                  <div className="font-medium text-gray-900 dark:text-dark-50">{p.displayName || 'Anonymous'}</div>
                  <div className="text-gray-500 dark:text-dark-400 text-xs mt-0.5">
                    {p.allocations.map((a) => CAUSE_LABELS[a.cause] ?? a.cause).join(', ')} · ${p.monthlySpendUsd.toFixed(0)}/mo estimated
                  </div>
                </div>
                <div className="font-medium text-gray-900 dark:text-dark-50">{formatUsd(p.projectedImpactUsd)}</div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
