import { useCallback, useEffect, useState } from 'react';
import { useAuthContext } from '../contexts/AuthContext';
import { workosFetch, WorkOsApiError } from '@grace/platform-core/services/workos';

export interface WorkshopParticipant {
  id: string;
  displayName: string | null;
  monthlySpendUsd: number;
  allocations: { cause: string; pct: number }[];
  illustrativeRatePct: number;
  projectedImpactUsd: number;
  createdAt: string;
}

export interface WorkshopEvidence {
  participantCount: number;
  totalProjectedImpactUsd: number;
  participants: WorkshopParticipant[];
}

/**
 * The "Pastor" stage of the Maya -> Me -> Us -> Pastor -> Real Pilot
 * workshop experience (North Star doc): real evidence generated by the
 * congregation's own interaction with the workshop simulation
 * (api/workshop/_simulate.ts), not a hypothetical pitch number.
 */
export function useWorkshopEvidence() {
  const { getAuthToken } = useAuthContext();
  const [data, setData] = useState<WorkshopEvidence | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [forbidden, setForbidden] = useState(false);

  const refresh = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    setForbidden(false);
    try {
      const result = await workosFetch<WorkshopEvidence>('/api/workshop/participants', getAuthToken);
      setData(result);
    } catch (err) {
      if (err instanceof WorkOsApiError && err.status === 403) {
        setForbidden(true);
      } else {
        setError(err instanceof Error ? err.message : 'Failed to load workshop evidence');
      }
    } finally {
      setIsLoading(false);
    }
  }, [getAuthToken]);

  useEffect(() => { void refresh(); }, [refresh]);

  return { data, isLoading, error, forbidden, refresh };
}
