import { useCallback, useEffect, useRef, useState } from 'react';
import { useAuthContext } from '../contexts/AuthContext';
import { workosFetch, WorkOsApiError } from '@grace/platform-core/services/workos';

export interface WorkshopWalletActivation {
  headlineCause: string;
  projectedMonthlyImpactUsd: number;
  createdAt: string;
}

export interface WorkshopParticipant {
  id: string;
  displayName: string | null;
  monthlySpendUsd: number;
  allocations: { cause: string; pct: number }[];
  illustrativeRatePct: number;
  projectedImpactUsd: number;
  createdAt: string;
  walletActivation: WorkshopWalletActivation | null;
}

export interface WorkshopEvidence {
  participantCount: number;
  totalProjectedImpactUsd: number;
  walletActivationCount: number;
  totalWalletProjectedImpactUsd: number;
  workshopUrl: string | null;
  participants: WorkshopParticipant[];
}

/** Auto-refresh cadence while "live" — slightly slower than workshop.html's
 *  own 8-second participant-facing poll, appropriate for a staff dashboard
 *  rather than an excitement screen. */
const POLL_INTERVAL_MS = 10_000;

/**
 * The "Pastor" stage of the Maya -> Me -> Us -> Pastor -> Real Pilot
 * workshop experience (North Star doc): real evidence generated by the
 * congregation's own interaction with the workshop simulation
 * (api/workshop/_simulate.ts), not a hypothetical pitch number.
 *
 * Auto-refresh starts PAUSED (isLive defaults false) so staff opening
 * this page outside a live session don't see it churn. Toggling it on
 * polls every POLL_INTERVAL_MS; it auto-pauses on a 403 (no point
 * retrying a permission failure every few seconds) and while the tab is
 * backgrounded, resuming automatically only if it was live before the
 * tab lost visibility.
 */
export function useWorkshopEvidence() {
  const { getAuthToken } = useAuthContext();
  const [data, setData] = useState<WorkshopEvidence | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [forbidden, setForbidden] = useState(false);
  const [isLive, setIsLive] = useState(false);
  const wasLiveBeforeHiddenRef = useRef(false);

  const refresh = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    setForbidden(false);
    try {
      const result = await workosFetch<WorkshopEvidence>('/api/workshop/participants', getAuthToken);
      setData(result);
    } catch (err) {
      if (err instanceof WorkOsApiError && err.status === 403) {
        setForbidden(true);
        setIsLive(false);
      } else {
        setError(err instanceof Error ? err.message : 'Failed to load workshop evidence');
      }
    } finally {
      setIsLoading(false);
    }
  }, [getAuthToken]);

  useEffect(() => { void refresh(); }, [refresh]);

  useEffect(() => {
    if (!isLive) return;
    const interval = setInterval(() => { void refresh(); }, POLL_INTERVAL_MS);
    return () => clearInterval(interval);
  }, [isLive, refresh]);

  useEffect(() => {
    function onVisibilityChange() {
      if (document.visibilityState === 'hidden') {
        wasLiveBeforeHiddenRef.current = isLive;
        setIsLive(false);
      } else if (wasLiveBeforeHiddenRef.current) {
        setIsLive(true);
      }
    }
    document.addEventListener('visibilitychange', onVisibilityChange);
    return () => document.removeEventListener('visibilitychange', onVisibilityChange);
  }, [isLive]);

  return { data, isLoading, error, forbidden, refresh, isLive, setLive: setIsLive };
}
