/**
 * GET /api/workshop/participants
 *
 * The "Pastor" stage of the Maya -> Me -> Us -> Pastor -> Real Pilot
 * workshop experience: real evidence generated by the congregation's own
 * interaction with the workshop simulation, not a hypothetical
 * projection made up for the pitch. Individual rows (display name if the
 * participant gave one, causes chosen, spend estimate, projected impact)
 * — this is the one workshop view that shows per-participant data, so
 * it's staff-only, unlike the public /simulate and /aggregate routes.
 *
 * Auth: Clerk Bearer (or demo bootstrap). Requires analytics.view — same
 * permission the workshop_simulations RLS staff-select policy checks
 * (migration 079), so this route and direct SQL/report access agree.
 */
import type { VercelRequest, VercelResponse } from '@vercel/node';
import { createClient } from '@supabase/supabase-js';
import { resolveStaffActor } from '../_lib/authz.js';

const SUPABASE_URL = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
    return res.status(503).json({ error: 'service_not_configured' });
  }
  if (req.method !== 'GET') return res.status(405).json({ error: 'method_not_allowed' });

  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, { auth: { persistSession: false } });
  const actor = await resolveStaffActor(req, res, supabase);
  if (!actor) return;

  if (!actor.permissions.has('analytics.view')) {
    return res.status(403).json({ error: 'insufficient_permission', required: 'analytics.view' });
  }

  const { data, error } = await supabase
    .from('workshop_simulations')
    .select('id, display_name, monthly_spend_micro_usd, allocations, illustrative_rate_bps, projected_impact_micro_usd, created_at')
    .eq('church_id', actor.churchId)
    .order('created_at', { ascending: false })
    .limit(500);

  if (error) {
    console.error('[workshop/participants] read failed', error);
    return res.status(500).json({ error: 'read_failed' });
  }

  const participants = (data ?? []).map(row => ({
    id: row.id,
    displayName: row.display_name,
    monthlySpendUsd: Number(row.monthly_spend_micro_usd) / 1_000_000,
    allocations: row.allocations,
    illustrativeRatePct: Number(row.illustrative_rate_bps) / 100,
    projectedImpactUsd: Number(row.projected_impact_micro_usd) / 1_000_000,
    createdAt: row.created_at,
  }));

  const totalProjectedImpactUsd = participants.reduce((sum, p) => sum + p.projectedImpactUsd, 0);

  return res.status(200).json({
    participantCount: participants.length,
    totalProjectedImpactUsd,
    participants,
  });
}
